server:
  port: ${SERVER_PORT}
  servlet:
    context-path: "/messenger/v1"
  security:
    tokenSecret: ${TOKEN_SECRET}

spring:
  redis:
    database: ${CACHE_DATABASE}
    host: ${CACHE_URL}
    port: ${CACHE_PORT}
    password: ${CACHE_SECRET}
    timeout: 5000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jms:
    servicebus:
      connection-string: ${SERVICE_HUB_URL}
      pricing-tier: ${SERVICE_HUB_TIER}
    email:
      queue-name: ${SERVICE_HUB_QUEUE}

logging:
  level:
    root: debug
