server:
  port: ${SERVER_PORT:8080}
azure:
  communication-service:
    connection-string: ${EMAIL_SERVER}
  storage:
    connection-string: ${MQ_SERVER}
    queue:
      recovery: ${RECOVERY_QUEUE}

logging:
  level:
    root: info