server:
  port: ${SERVER_PORT}
  servlet:
    context-path: "/messenger/v1"
  security:
    tokenSecret: ${TOKEN_SECRET}

spring:
  redis:
    database: ${CACHE_DATABASE}
    host: ${CACHE_URL}
    port: ${CACHE_PORT}
    password: ${CACHE_SECRET}
    timeout: 5000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${MESSENGER_HOST}
    port: ${MESSENGER_PORT}
    username: ${MESSENGER_USERNAME}
    password: ${MESSENGER_SECRET}
    messenger:
      queue: ${MESSENGER_QUEUE}

logging:
  level:
    root: debug
