server:
  port: ${SERVER_PORT:8080}
  jackson:
    serialization:
      write-dates-as-timestamps: false
azure:
  communication-service:
    connection-string: ${EMAIL_SERVER}
    email: ${EMAIL_DOMAIN}
  messenger:
    connection-string: ${MQ_SERVER}
    recovery:
      queue: ${RECOVERY_QUEUE}
    admin-notification:
      queue: ${ADMIN_NOTIFICATION_QUEUE}
    core-notification:
      queue: ${CORE_NOTIFICATION_QUEUE}

client:
  equaly:
    url: ${EQUALY_URL:http://localhost:4200}

logging:
  level:
    root: info