server:
  port: ${SERVER_PORT:8080}
azure:
  communication-service:
    connection-string: ${EMAIL_SERVER}
    email: ${EMAIL_DOMAIN}
  messenger:
    connection-string: ${MQ_SERVER}
    recovery:
      queue: ${RECOVERY_QUEUE}
    admin-notification:
      queue: ${ADMIN_NOTIFICATION_QUEUE}
    core-notification:
      queue: ${CORE_NOTIFICATION_QUEUE}

client:
  reset-password:
    url: ${RESET_PASSWORD_URL}

logging:
  level:
    root: info